### PR TITLE
changing HTML tempfile mode from 'w+b' to 'w'

### LINKED ISSUE #20: Generating HTML report fails on Py3
```python
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/vaxrank", line 9, in <module>
    load_entry_point('vaxrank', 'console_scripts', 'vaxrank')()
  File "/Users/iskander/code/vaxrank/vaxrank/cli.py", line 161, in main
    pdf_report_path=args.output_pdf_report)
  File "/Users/iskander/code/vaxrank/vaxrank/report.py", line 171, in make_pdf_report
    _make_report(template_data, f, 'templates/template.html')
  File "/Users/iskander/code/vaxrank/vaxrank/report.py", line 134, in _make_report
    file_handle.write(report)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tempfile.py", line 399, in func_wrapper
    return func(*args, **kwargs)
TypeError: 'str' does not support the buffer interface
```

### PR DESCRIPTION
**Pull request by julia326**
Fixes #20

### CODE REVIEW

**Comment by iskandr** [comment]
LGTM

**Comment by iskandr** [comment]
Increase the version?

**Comment by ihodes** [comment]
Might be good to throw a test in there, some invocation that calls vaxrank with all reports. That way we can catch this in the future.

**Comment by iskandr** [comment]
@ihodes Added an issue for it https://github.com/hammerlab/vaxrank/issues/24

**Pull request merged**
